name: syberwaifu
description: A new Flutter project.
version: 0.1.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  chat_gpt_sdk: ^2.0.7
  contextmenu: ^3.0.0
  dropdown_button2: ^2.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.0.14
  provider: ^6.0.5
  screen_capturer: ^0.1.3
  sqflite_common: ^2.4.3
  sqflite_common_ffi: ^2.2.2
  syncfusion_flutter_datagrid: ^21.1.41
  syncfusion_localizations: ^21.1.41
  uuid: ^3.0.7
  window_manager: ^0.3.1
  auto_updater: ^0.1.6
  pager: ^0.0.5
  extended_image: ^7.0.2
  file_picker: ^5.2.10
  image: ^4.0.17
  path: ^1.8.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/syberwaifu.sql
    - assets/default_ai_avatar.png
    - assets/default_user_avatar.png
flutter_intl:
  enabled: true
  main_locale: zh_CN

