name: syberwaifu
description: A new Flutter project.
version: 0.1.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  chat_gpt_sdk: ^3.0.3
  contextmenu: ^3.0.0
  dropdown_button2: ^2.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.0.14
  provider: ^6.0.5
  sqflite_common: ^2.4.3
  sqflite_common_ffi: ^2.2.2
  syncfusion_flutter_datagrid: 24.2.6
  syncfusion_localizations: ^24.2.8
  uuid: ^4.3.3
  window_manager: ^0.3.1
  auto_updater: ^0.1.6
  pager: ^0.0.5
  extended_image: ^8.2.0
  file_picker: ^6.1.1
  image: ^4.0.17
  path: ^1.8.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/syberwaifu.sql
    - assets/default_ai_avatar.png
    - assets/default_user_avatar.png
flutter_intl:
  enabled: true
  main_locale: zh_CN

