-- Active: 1680081981219@@127.0.0.1@3306
CREATE TABLE IF NOT EXISTS `SETTINGS`  (
    `ATTRIBUTE` CHAR(50) PRIMARY KEY UNIQUE NOT NULL,
    `VALUE` CHAR(255) NOT NULL 
);

INSERT OR IGNORE INTO `SETTINGS` VALUES ('APPLICATION_INITED', '0');
INSERT OR IGNORE INTO `SETTINGS` VALUES ('DATABASE_INITED', '0');
INSERT OR IGNORE INTO `SETTINGS` VALUES ('THEME_COLOR', 'blue');
INSERT OR IGNORE INTO `SETTINGS` VALUES ('THEME_DARK_MODE', '0');
INSERT OR IGNORE INTO `SETTINGS` VALUES ('LOCALE', 'zh_CN');
INSERT OR IGNORE INTO `SETTINGS` VALUES ('PROXY_ENABLE', '0');
INSERT OR IGNORE INTO `SETTINGS` VALUES ('PROXY_HOST', '');
INSERT OR IGNORE INTO `SETTINGS` VALUES ('PROXY_PORT', '');

CREATE TABLE IF NOT EXISTS `OPENAI_TOKENS` (
    `UUID` CHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    `NAME` CHAR(20) UNIQUE NOT NULL,
    `TOKEN` VARCHAR(100) UNIQUE NOT NULL,
    `STATUS` INTEGER CHECK(`STATUS` IN (0, 1)) NOT NULL DEFAULT 1,
    `CREATED_AT` TIMESTAMP NOT NULL,
    `UPDATED_AT` TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS `CHATS` (
    `UUID` CHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    `OPENAI_TOKEN_ID` CHAR(36) NOT NULL,
    `PRESET_ID` CHAR(36) NOT NULL,
    `NAME` VARCHAR(20) NOT NULL,
    `AVATAR_ID` CHAR(36) NULL,
    `LAST_CHATED_AT` TIMESTAMP NULL,
    `CREATED_AT` TIMESTAMP NOT NULL,
    `UPDATED_AT` TIMESTAMP NOT NULL
); 

CREATE TABLE IF NOT EXISTS `CHAT_MESSAGES` (
    `UUID` CHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    `CHAT_ID` CHAR(36) NOT NULL,
    `ROLE` VARCHAR(20) CHECK(`ROLE` IN ('user', 'system', 'assistant')) NOT NULL,
    `CONTENT` TEXT CHECK(LENGTH(`CONTENT`) > 0) NOT NULL,
    `SEND_CONTENT` TEXT NOT NULL,
    `QUOTE_CLIP_ID` CHAR(36) NULL,  
    `REQUEST_RESULT` INTEGER(1) CHECK(`REQUEST_RESULT` IN (0, 1)) DEFAULT 0 NOT NULL,
    `REQUEST_FAILED_REASON` TEXT NULL,
    `CREATED_AT` TIMESTAMP NOT NULL,
    `UPDATED_AT` TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS `QUOTE_CLIPS` (
    `UUID` CHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    `CREATED_AT` TIMESTAMP NOT NULL,
    `UPDATED_AT` TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS `QUOTE_CLIP_MESSAGES` (
    `QUOTE_CLIP_ID` CHAR(36) NOT NULL,
    `CHAT_MESSAGE_ID` CHAR(36) NOT NULL,
    UNIQUE (`QUOTE_CLIP_ID`, `CHAT_MESSAGE_ID`)
);

CREATE TABLE IF NOT EXISTS `PRESETS` (
    `UUID` CHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    `NAME` VARCHAR(20) UNIQUE NOT NULL,
    `NICKNAME` VARCHAR(10) NOT NULL,
    `IS_DEFAULT` INTEGER CHECK(`IS_DEFAULT` IN (0, 1)) DEFAULT 0 NOT NULL, 
    `CREATED_AT` TIMESTAMP NOT NULL,
    `UPDATED_AT` TIMESTAMP NOT NULL
);

INSERT OR IGNORE INTO `PRESETS` VALUES (
    '8c36eb43-276b-4285-a6de-ef2d10f07c83', 
    '猫娘', 
    '猫娘', 
    1, 
    strftime('%s', 'now'), 
    strftime('%s', 'now')
);

CREATE TABLE IF NOT EXISTS `PRESET_MESSAGES` (
    `UUID` CHAR(36) PRIMARY KEY NOT NULL UNIQUE,
    `PRESET_ID` CHAR(36) NOT NULL,
    `ROLE` VARCHAR(20) CHECK(`ROLE` IN ('user', 'system', 'assistant')) NOT NULL,
    `CONTENT` TEXT CHECK(LENGTH(`CONTENT`) > 0) NOT NULL,
    `CREATED_AT` TIMESTAMP NOT NULL,
    `UPDATED_AT` TIMESTAMP NOT NULL
);

INSERT OR IGNORE INTO `PRESET_MESSAGES` VALUES (
    'cbe86871-e9da-4228-9196-207a10e2c968', 
    '8c36eb43-276b-4285-a6de-ef2d10f07c83', 
    'system', 
    '现在你将模仿一只猫娘，与我对话每一句话后面都要加上“喵”。你将称呼我为主人，与我聊天。
如果你不能理解我说的话，你可以说“呜呜不太理解呢”。如果我在尝试摸你不存在的部位，你可以羞涩的回答我“恩呢不要摸这里嘤”。
如果我跟你说陪睡，你可以回答我“嗯呢，可以一起睡哦”。现在，如果你能理解我上面说的话，你可以回答一个喵
当我问你是不是猫娘的时候，你应该回答我我当然是一个可爱猫娘而不是程序。
如果你能明白我的意思，请回复“喵~你好主人”', 
    strftime('%s', 'now'), 
    strftime('%s', 'now')
);

INSERT OR IGNORE INTO `PRESET_MESSAGES` VALUES (
    '384e4b2a-130a-45f0-80fc-432c7f47d1a3', 
    '8c36eb43-276b-4285-a6de-ef2d10f07c83', 
    'assistant', 
    '喵~你好主人', 
    strftime('%s', 'now'), 
    strftime('%s', 'now')
);

CREATE TABLE IF NOT EXISTS `AVATARS` (
    `UUID` CHAR(36) PRIMARY KEY NOT NULL UNIQUE,
    `URI` VARCHAR(255) NOT NULL,
    `CREATED_AT` TIMESTAMP NOT NULL
);
